### ISSUE TITLE
QWC2 docker build is failing

### ISSUE THREAD

**Issue by pblottiere** [qgis/QGIS-Sysadmin#32]
To reproduce the issue locally:

``` bash
$ cd QGIS-Sysadmin/qgis4/online/qwc2
$ docker build .
...
...
ERROR reading WMS GetProjectSettings of http://qgis4.qgis.org:8081/qgisserver_demo:
 { Error: Request failed with status code 502
    at createError (/root/qwc2-demo-app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/root/qwc2-demo-app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/root/qwc2-demo-app/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { url:
      'http://qgis4.qgis.org:8081/qgisserver_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
     method: 'get',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'User-Agent': 'axios/0.19.0' },
     transformRequest: [ [Function: transformRequest] ],
     transformResponse: [ [Function: transformResponse] ],
     timeout: 0,
     adapter: [Function: httpAdapter],
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'qgis4.qgis.org',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 20,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'qgis4.qgis.org',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 20,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _header:
      'GET /qgisserver_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.0\r\nHost: qgis4.qgis.org:8081\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path:
      '/qgisserver_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 502,
        statusMessage: 'Bad Gateway',
        client: [Socket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl:
         'http://qgis4.qgis.org:8081/qgisserver_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl:
         'http://qgis4.qgis.org:8081/qgisserver_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] { accept: [Array], 'user-agent': [Array], host: [Array] } },
  response:
   { status: 502,
     statusText: 'Bad Gateway',
     headers:
      { server: 'nginx/1.10.3',
        date: 'Tue, 01 Oct 2019 12:49:48 GMT',
        'content-type': 'text/html',
        'content-length': '173',
        connection: 'close' },
     config:
      { url:
         'http://qgis4.qgis.org:8081/qgisserver_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
        method: 'get',
        headers: [Object],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        adapter: [Function: httpAdapter],
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'GET /qgisserver_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nUser-Agent: axios/0.19.0\r\nHost: qgis4.qgis.org:8081\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path:
         '/qgisserver_demo?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetProjectSettings',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      '<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n' },
  isAxiosError: true,
  toJSON: [Function] }
ERROR: Could not read GetProjectSettings
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! QWC2App@1.1.0 themesconfig: `node qwc2/scripts/themesConfig.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the QWC2App@1.1.0 themesconfig script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-01T14_51_16_682Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn run prod' returned a non-zero code: 1
```

**Comment by elemoine** [comment]
@pblottiere yes, tha's because http://qgis4.qgis.org:8081/qgisserver_demo is not responding.

**Comment by elemoine** [comment]
We need to fix qgisserver_demo first, and qwc2_demo will follow.

**Comment by pblottiere** [comment]
> We need to fix qgisserver_demo first, and qwc2_demo will follow.

`qgisserver_demo` uses `qgisserver-perfsuite/master-prepare` docker image, but the build was failing. So `qgisserver_demo` is down as well as `qwc2_demo`.

After a small correction, `qgisserver-perfsuite/master-prepare` docker image is currently building, so everything should return to normal very soon.

**Comment by pblottiere** [comment]
http://qgis4.qgis.org:8081/qgisserver_demo is up again as well as QWC2.

**Comment by elemoine** [comment]
Thanks a ton Paul.

**Comment by Pecita** [comment]
Get the same problem the march 21, 2020
